from dataclasses import dataclass
from datetime import datetime


@dataclass(frozen=True)
class SimulatedEnergyTelemetry:
    """Telemetry generated by the simulated EOS IoT provider."""

    power_watts: float
    voltage: float
    current: float
    frequency: float
    energy_kwh: float
    timestamp: datetime
    reading_type: str
    phase: str
